### ISSUE TITLE
'!-' Comment 

### ISSUE THREAD

**Issue by appleparan** [textmate/fortran.tmbundle#1]
Actually, I am using sublime text 2 but I think it could be helpful.
In 'Fortarn-Modern' syntax highlighting(Fortran - Modern.tmLanguage), '!-' comment does not work accurately.
For example, 

!--------------------- !- comment-1
! Some comments
!--------------------- !- comment-2
! Some comments 2

in this case, In 'some comments' and 'some comments 2' are not shown as comments. I switched a section of capturing (^[ \t]+)?(?=!) and that of (^[ \t]+)?(?=!-) , then it worked properly.

**Comment by infininight** [comment]
This works for me on TextMate 2 as is. It's possible that Sublime Text 2 doesn't support some of the new features we allow in 2.0, though I don't see what that would be in the begin match.
