### ISSUE TITLE
Indenting/dedenting ignores comments and continuation symbols

### ISSUE THREAD

**Issue by dpo** [textmate/fortran.tmbundle#11]
I'm using the "punch-card" mode to edit Fortran 77 code. If I select a bock of code and hit Command-], commented lines are indented entirely, including the character in column 1. Similarly, if one line has a continuation character in column 6, it is indented as well.

**Comment by infininight** [comment]
Can you provide a code sample and point out the places it fails.

**Comment by dpo** [comment]
#### Example 1: continuation character in column 6:

```
      call dicf(n,nnz,a,diag,col_ptr,row_ind,p,info,
     +                indr,indf,list,w)
```

I select those two lines and hit Command-]. Result:

```
         call dicf(n,nnz,a,diag,col_ptr,row_ind,p,info,
        +                indr,indf,list,w)
```

The continuation character moved. Fortran 77 no longer treats the second line as continuation of the first.

#### Example 2: comment character in column 1:

```
c        Exit if the current pivot is zero.

         if (diag(j) .eq. zero) then
            info = -j
            return
         end if
```

I select all those lines and hit Command-]. Result:

```
   c        Exit if the current pivot is zero.

            if (diag(j) .eq. zero) then
               info = -j
               return
            end if
```

The comment character moved. Fortran 77 no longer treats the first line as a comment.

In both cases, hitting Command-[ returns everything to the initial state.

**Comment by infininight** [comment]
OK, I understand the issue now. TextMate doesn't have any method to say that something should be ignored when indenting/de-indenting, so currently this is not possible.

**Comment by dpo** [comment]
Thank you for looking into this. I'm actually using this Fortran mode in Sublime Text. Any idea if selective indenting exists over there?

**Comment by sorbits** [comment]
It sounds like you should just overload 
<kbd>⌘]</kbd> for `source.fortran` to skip the leading `+` or `c`.

We could add that to the default bundle, but given that you’re not using TextMate, it’s uncertain that such addition would work for the editor you use.

**Comment by dpo** [comment]
Thanks. Of course TextMate Fortran users will normally want the same. Note also that the symbols themselves don't matter, only that they are located in column 1 or 6.
