### ISSUE TITLE
Second line of comments on 'Fortran - Modern' not recognized

### ISSUE THREAD

**Issue by filipesmg** [textmate/fortran.tmbundle#14]
I use Fortran (Modern) with Sublime Text (now I'm using version 3) and there was just a little glitch handling comments. Look at this example:
![Second line not recognized as a comment](https://f.cloud.github.com/assets/2450145/1818202/4c0b738c-6fea-11e3-94b0-25cfca4f526a.png)
As you can see, the second line starts with an exclamation mark, but it's not recognized. But if I start the first line with "! " (including a space), then everything works:
![Second line correctly recognized as a comment](https://f.cloud.github.com/assets/2450145/1818208/5d7a0b7e-6fea-11e3-8b67-d8acd3e30409.png)
If I put a dash after the ! of the second line, it reconizes it as a comment, but the problem goes to the third line:
![Third line not recognized as a comment](https://f.cloud.github.com/assets/2450145/1818211/6e8eacb2-6fea-11e3-840c-aaedc8167b18.png)
I don't understand the language of the syntax file, but I've looked at the MinimalFortran package (https://github.com/315234/MinimalFortran) to fix this (this package works great and can be installed using Package Control, but it misses lots of syntaxes). I just changed the

```
<string>!-</string>
```

to

```
<string>[!]</string>
```

on the "Fortran - Modern.tmLanguage" file and it all worked:
![All lines correctly recognized as comments](https://f.cloud.github.com/assets/2450145/1818212/822b9b7c-6fea-11e3-8ff7-62343bd89c61.png)
I don't know if this can cause any conflict anywhere else, so maybe someone can check if this fix works and if so, change the file on the package.

**Comment by infininight** [comment]
I believe the issue here is that Sublime does not support some of the new TextMate 2.0 grammar features, in this case how 2.0 treats the \G assertion. Due to this you will need to use the 1.x fork we created:

https://github.com/textmate/fortran.tmbundle/tree/textmate-1.x

It is no longer being updated but should function correctly with Sublime.

**Comment by filipesmg** [comment]
Thank you for the answer! I'll use this other version.
