### ISSUE TITLE
Line after comment not highlighting correctly

### ISSUE THREAD

**Issue by rlh1994** [textmate/fortran.tmbundle#16]
The first word on the line after a comment isn't highlighting correctly, if there is a space before the word it highlights fine, if there is a line between it works fine, just not if it starts straight away.
![screenshot 2014-07-24 20 04 32](https://cloud.githubusercontent.com/assets/8260415/3693287/861310e8-1365-11e4-9754-da0c4daa88cb.png)

I've also tested it and it doesn't matter where the comment starts on the line above. Problem in Fortran-Modern using Sublime 2 and 3

**Comment by infininight** [comment]
Sublime does not yet support some new grammar features from 2.0, you'll need to use the 1.x branch:

https://github.com/textmate/fortran.tmbundle/tree/textmate-1.x
