### ISSUE TITLE
Syntax Highlighting - Allocatable Command

### ISSUE THREAD

**Issue by shuguo77** [textmate/fortran.tmbundle#17]
The allocatable command is not highlighted.  Could you add the coloring to this command?

Thanks!

**Comment by GeorgeWeber** [comment]
This has also been an issue for me.  The "only" command also does not become highlighted.  Is there somewhere in one of the files where I can add these keywords?

**Comment by infininight** [comment]
Please provide a code sample where the highlighting does not work.

**Comment by infininight** [comment]
In looking at further issues I believe I found a case where it wasn't working. I believe it should now always match. If it does not work after 24 hours then provide a code sample and reopen the issue.
