### ISSUE TITLE
Highlighting problems with ST3, build 3065

### ISSUE THREAD

**Issue by fredcouderc** [textmate/fortran.tmbundle#18]
When you write a large number of SUBROUTINE in a Fortran file, there are 2 problems of highlighting:

a minor first one
![first](https://cloud.githubusercontent.com/assets/2278361/5413356/1daee00c-8216-11e4-8100-1c81773d7d03.png)
a major second !
![second](https://cloud.githubusercontent.com/assets/2278361/5413358/233324e8-8216-11e4-9f2d-a9fe16d40a01.png)
all is white after ...

a kind of problem of buffer size ? another one ?

thanks !

**Comment by infininight** [comment]
Not familiar with Sublime so unsure what the issue could be. Looking at the grammar this is a reasonably simplistic rule, a begin/end rule to match functions. The only thing that might be throwing it is the use of `\G` in the match inside the function rule.

I would take a look at the `\G` match to see if it is being handled correctly and if it is report this as a bug in Sublime Text, don't see an issue with the grammar itself.
