### ISSUE TITLE
Indentation doesn't work well

### ISSUE THREAD

**Issue by dongli** [textmate/fortran.tmbundle#2]
I installed Fortran bundle in TextMate2, and write codes in "Fortran - Modern". But the indentation doesn't work well with `module` block.

When I type "tab" to indent one level, and type some characters, they just jump to the beginning of the line.

**Comment by infininight** [comment]
Can you provide some sample code and how it should be indented.

**Comment by dongli** [comment]
@infininight Any code will show this problem, such as:

``` Fortran
module mod

    implicit none ! HERE

end module mod
```

TextMate will jump to the beginning of the line when I entered "tab", and type "implicit none".

**Comment by infininight** [comment]
I added a lot to the indention rules, comment again if you find anything missing.
