### ISSUE TITLE
Only "compile single file bundle" is available, how could I use it to compile a project with multiple files?

### ISSUE THREAD

**Issue by LittleTrain1992** [textmate/fortran.tmbundle#22]

**Comment by infininight** [comment]
The command here basically just runs `gfortran /path/to/file`, so the first step would be to determine how to use gfortran or your compiler of choice to compile a project and edit the command (or duplicate and edit) to add the needed flag/etc. If it is just a flag though the command already calls $TM_FFLAGS as an environment variable that by default is empty.
