### ISSUE TITLE
Fortran lines starting with ! not treated as comments in GitHub markdown

### ISSUE THREAD

**Issue by warrickball** [textmate/fortran.tmbundle#25]
I've followed a trail of packages to determine that this module is what GitHub's syntax highlighter uses to interpret Fortran source. If I've got that wrong, sorry! Feel free to send me off in the right direction.

I noticed that GitHub's Fortran syntax highlighting doesn't recognise lines starting `!` as comments. e.g.

```Fortran
c recognised as starting a comment
! is not recognised as starting a comment
x = 1 ! This comment is not recognised either.
! integer function should not be highlighted
```

GitHub's help on [creating and highlighting code blocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) has a [list of third-party grammars](https://github.com/github/linguist/blob/master/vendor/README.md) that are used for syntax highlighting, which is what brought me here.

**Comment by jacobwilliams** [comment]
I also noticed that the GitHub Fortran syntax highlighter was broken. It used to work though, and fairly recently. There are also other problems, not just the comment lines.

This repo hasn't been updated in 2 years though. So... how can this be the source of the problem?

**Comment by warrickball** [comment]
I haven't been paying attention closely enough to notice that Fortran highlighting was working before but I fully agree that, if it broke since this repo was last updated, this can't be the problem. I'll close this in favour of [the issue](https://github.com/github/linguist/issues/4799) you already raised with [Linguist](https://github.com/github/linguist).
