### ISSUE TITLE
Soubroutine after comment not hilighted

### ISSUE THREAD

**Issue by 315234** [textmate/fortran.tmbundle#5]
For example

! this is a comment
subroutine subname()
...

In the above the subroutine line is not highlighted and is not recognised as a symbol.

**Comment by infininight** [comment]
Not able to reproduce this, are you using the modern syntax?

**Comment by 315234** [comment]
Yes, I can reproduce it with the Modern syntax but it is highlighted and identified correctly with the Punchcard syntax. Placing a new line between comment and subroutine declaration makes the highlighting work.

Looking through the Fortran Modern file, there are some references to ruby left in the sections regarding comments. Perhaps this has something to do with it?

**Comment by 315234** [comment]
I have updated to the latest TextMate and Fortran bundle and the problem is fixed.
