### ISSUE TITLE
Many Arguments in Subroutine

### ISSUE THREAD

**Issue by mmanuel26** [textmate/fortran.tmbundle#8]
I have highlight issues when I write continuation lines in my subroutines. Here is a picture of  one of my subroutines: 

![Selection_001](https://f.cloud.github.com/assets/3615417/164580/f7bbbe48-78bb-11e2-857f-69544286ae41.png)

My goal is to develop several subroutines in ABAQUS CAE, and your syntax highlight save my day! However I wish you can tell me how I fix the problem. Here is another screenshot of ABAQUS CAE subroutine that I have to develop. Instead of orange I get white colors for the arguments. 

![Selection_002](https://f.cloud.github.com/assets/3615417/164583/9ec4975a-78bc-11e2-9880-68e92aef242c.png)

Keep the good work, you are our Fortran savior ( Fortran users with Sublime Text2)! Please help me!

**Comment by infininight** [comment]
Currently the match for functions matches the opening part as a single match which means it must be contained on a single line. What would need to be done is to break the attribute matching into a separate begin/end match inside the first. Dropping by our IRC chatroom would be a good idea as you can ask questions as you look at the grammar.

**Comment by mmanuel26** [comment]
Where can I find your IRC?

**Comment by infininight** [comment]
http://macromates.com/community

**Comment by infininight** [comment]
Note that this is a 2.0 specific change, there are several 2.0 specific changes in the main branch that won't work in Sublime Text. We have an 1.x branch for 1.x and Sublime users.

https://github.com/textmate/fortran.tmbundle/tree/textmate-1.x
