### ISSUE TITLE
Fortran Modern - No highlighting after line ending with a comment

### ISSUE THREAD

**Issue by rmcdermo** [textmate/fortran.tmbundle#9]
Highlighting seems to be broken for the following example:

integer, parameter :: my_int_1 = 1  ! in this case "integer" is highlighted [do not skip a line]
integer, parameter :: my_int_2 = 2  ! in this case "integer" is not highlighed

but ...

integer, parameter :: my_int_1 = 1  ! in this case "integer" is highlighted
[skip a line]
integer, parameter :: my_int_2 = 2  ! now "integer" is highlighed

**Comment by rmcdermo** [comment]
I also just noticed that this has something to do with the first column.  For example, the following works fine:

integer, parameter :: my_int_1 = 1 ! in this case "integer" is highlighted [do not skip a line]
[space]integer, parameter :: my_int_2 = 2 ! now "integer" is highlighted correctly

**Comment by infininight** [comment]
Not seeing this behavior, are you using 2.0 of TextMate?

**Comment by rmcdermo** [comment]
I thought I was using the latest.  I downloaded the latest version and tried it just before I posted the issue.  But, I will double check...

**Comment by infininight** [comment]
Closed due to lack of followup.
